DROP TABLE IF EXISTS usuarios;

CREATE TABLE IF NOT EXISTS usuarios(
    username VARCHAR(100) NOT NULL PRIMARY KEY,
    password VARCHAR(50) NOT NULL,
    token VARCHAR(130) NOT NULL,
    timestamps TIMESTAMPS DEFAULT CURRENT_TIMESTAMP
);